### ISSUE TITLE
old sa-learn (or Razor2.pm) bug

### ISSUE THREAD

**Issue by joximu** [MailCleaner/MailCleaner#171]
./learn_ham.sh <fiile>
Use of uninitialized value $type in numeric eq .....

see here:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=784649

and here:
https://bz.apache.org/SpamAssassin/show_bug.cgi?id=7018

```
--- /usr/local/share/perl/5.20.2/Mail/SpamAssassin/Plugin/Razor2.pm_o   2014-02-07 09:36:27.000000000 +0100
+++ /usr/local/share/perl/5.20.2/Mail/SpamAssassin/Plugin/Razor2.pm     2020-04-28 10:27:00.953411000 +0200
@@ -115,7 +115,7 @@
     setting => 'razor_timeout',
     is_admin => 1,
     default => 5,
-    type => $Mail::SpamAssassin::Conf::CONF_TYPE_DURATIION,
+    type => $Mail::SpamAssassin::Conf::CONF_TYPE_DURATION,
   });
 
 =item razor_config filename
```

My install is based on the MailCleaner_OVA_2019022601

**Comment by p-rolle** [comment]
Hello,

Thanks for this.
To get in contact with our services, please use one of the following communication channels :

    either you are running an Enterprise Edition of MailCleaner and should therefore have credentials to ask questions using https://support.mailcleaner.net/
    either you are running a Community Edition of MailCleaner in which case we provide forums where you can get help from other Community Edition users at https://forum.mailcleaner.org/

Best regards,

**Comment by joximu** [comment]
Hi
I don't need help with this - just found a bug and wanted to tell/help...

I thought here is right place to drop this...

Regards
