### ISSUE TITLE
Why blacklist and what is the reason?

### ISSUE THREAD

**Issue by sistemasnegros** [MailCleaner/MailCleaner#175]
I am having this problem with some email, despite being whitelisted, for some reason it says blacklisted and quarantines it

source email

`Contents of the message (Identifier: 1jWlJY-0005og-E1)

Received: from a8-126.smtp-out.amazonses.com ([54.240.8.126])
by xxxx.xxxxx.xxxx stage1 with esmtps
(Exim MailCleaner)
id 1jWlJQ-0005mO-Ly
for <xxxxx@xxx.xxx>
from <01000171f067f692-741f6c2b-9d1d-46ba-ab05-0033e362f4ac-000000@amazonses.com>; Thu, 07 May 2020 13:32:08 -0500
X-MailCleaner-SPF: 	pass
DKIM-Signature: 	v=1; a=rsa-sha256; q=dns/txt; c=relaxed/simple;
s=q4go33brjx4v5s4e4l46iko4rupbtqln; d=cen.biz; t=1588876277;
h=MIME-Version:From:To:Date:Subject:Content-Type:Message-ID;
bh=BPnAMpW5rZJU1K29qjRLZwI1pRYOguiuKsVNbR6o/1k=;
b=CCVZXeGF/5rmOgBtRbdjb1HYNRVPWs28/XUjWoV4+YISkFLijZoyKn4UhtQ+cHoL
y/B1UgZNaubKI4xAy9qGoRcW4N6PznFL0YsgzONyXiLhvPxQe8Xh315P5C5dKcApynU
rBK0fztuw5Lzcvk5Oo0UgcemDIIzhvJioANvEtYQ=
DKIM-Signature: 	v=1; a=rsa-sha256; q=dns/txt; c=relaxed/simple;
s=224i4yxa5dv7c2xz3womw6peuasteono; d=amazonses.com; t=1588876277;
h=MIME-Version:From:To:Date:Subject:Content-Type:Message-ID:Feedback-ID;
bh=BPnAMpW5rZJU1K29qjRLZwI1pRYOguiuKsVNbR6o/1k=;
b=SD3pB2VPlruwLVuJk6q81bwpR4p/ZZRtzwqu9rQ8DRe1ebb1Dlm7AJXEQBxqa27n
5VkDrx1u4Km7//7jONZioPuSBts4JJYqTY0xZoGTgQghXVHAVWH6l49aWIwuCf+Pbfk
S1iwOxSi+vkFRvkwcsj8ZPDlVDelBbaFD9XcIlQU=
X-Sender: xxxxxxx@cen.biz
X-Receiver: xxxxx@xxxxxxxx.xxx
MIME-Version: 1.0
From: xxxxxxx@cen.biz
To: xxxxx@xxxxxxxx.xxx
Date: Thu, 7 May 2020 18:31:17 +0000
Subject: 	=?utf-8?B?Tm90aWZpY2FjacOzbiBDb21wcm9iYW50ZSBO4oGwIFRFNDUzOTcgZW1pdGlkbyBwb3IgU0lFTUVOUyBIRUFMVEhDQVJFIFMuQS5TLg==?=
Content-Type: 	multipart/mixed;
boundary=--boundary_218695_39868a69-66b5-4d20-a2a2-e711cfb62dff
Message-ID: <01000171f067f692-741f6c2b-9d1d-46ba-ab05-0033e362f4ac-000000@email.amazonses.com>
X-SES-Outgoing: 2020.05.07-54.240.8.126
Feedback-ID: 1.us-east-1.xCzgCNYhi8hKtKe1wbsMD2wC7YxeHmk0s2kl5AcD4V8=:AmazonSES
X-Newsl: 	is not newsletter (0.0/5.0)
X-NiceBayes: is not spam (49.99%)
X-MailCleaner-Information: Please contact for more information
X-MailCleaner-ID: 1jWlJY-0005og-E1
X-MailCleaner: Found to be clean
X-MailCleaner-SpamCheck: not spam, Newsl (score=0.0, required=5.0, )
X-MailCleaner-Status: Blacklisted (cc98730b43e60c9e2ed8d4dbec36f94f)`

X-MailCleaner-Status: Blacklisted (cc98730b43e60c9e2ed8d4dbec36f94f)

domain from is *@amazonses.com, IPs 54.240.8.0/21 this included in whitelist.

**Comment by p-rolle** [comment]
Hello,
We dont use Github to provide support for our customers :
 - either you are running an Enterprise Edition of MailCleaner and should therefore have credentials to ask questions using https://support.mailcleaner.net/
 - either you are running a Community Edition of MailCleaner in which case we provide forums where you can get help from other Community Edition users at https://forum.mailcleaner.org/

In your case, you probably blacklisted a text string that is also hit by the sender s domain. Since the blacklists are applied before the whitelists, this explain the issue.

You can use the command line tool
/usr/mailcleaner/bin/check_match_wwlists.pl
to find out which rules have been triggered by your mail.

Best regards,

**Comment by sistemasnegros** [comment]
We are sorry to have used issues from github to report this problem, but in the mail cleaner community forum we did not receive a response, in the diagnoses that we have made to this problem we found no reason to have been blacklisted, because the domains and Neither the IP addresses were blacklisted, and the whitelist is not working for this case, so we think it is a bug

I will test  your recomendations!
