### ISSUE TITLE
New domain names not accepted as EHLO/HELO indentity

### ISSUE THREAD

**Issue by victorlclopes** [MailCleaner/MailCleaner#186]
Hi there!

I came across a little bug in the "Force HELO" configuration in **Base system > DNS settings** that I felt like reporting here, because it seems like something relatively simple that could be fixed in a next update.

The page does not allow you to enter a domain like .services. Now we have available an infinity of domains like .energy, .cloud, .solutions and I see how these could be easily mistaken by internal domains like .local and .corp.

![image](https://user-images.githubusercontent.com/27737616/83867289-90892600-a6ff-11ea-9f46-694539393fdc.png)

We're in the process of migrating our domain to a .services for example.

Thank you,

Victor.

**Comment by JonasN78** [comment]
You can manually update this with the correct tld through SSH. 
/etc/mailcleaner.conf >> HELONAME = mail.domain.services
Restart your inbound queue after updating.
Can be different HELO on different cluster members too.

**Comment by p-rolle** [comment]
Thanks for reporting this issue
