### ISSUE TITLE
OVA/OVF Issues & Installation Script

### ISSUE THREAD

**Issue by bradjtrammell** [MailCleaner/MailCleaner#228]
So I know there is a place on your website where you can go and download the most recent verison of the OVA, but ESXi doesn't allow OVA/OVF import without a VMDK, so that's somewhat useless unless you're using VMWare Workstation. Additionally, is there a way, or can you easily create a way to use a newer version of Debian?

I'd like to see an actual install script or ISO (that's less than 6 years old), to setup a physical server or VM.

How likely is any of this to happen, it's kind of a massive hindrance to deploy your community software...

**Comment by p-rolle** [comment]
Hello,
We dont use Github to provide support for our customers :

  -  either you are running an Enterprise Edition of MailCleaner and should therefore have credentials to ask questions using https://support.mailcleaner.net/
  -  either you are running a Community Edition of MailCleaner in which case we provide forums where you can get help from other Community Edition users at https://forum.mailcleaner.org/

You can get more information on your question here :
https://forum.mailcleaner.org/viewtopic.php?f=1&t=3109

Best regards,
