### ISSUE TITLE
SPam quarantaine not showing anything

### ISSUE THREAD

**Issue by serpentes80** [MailCleaner/MailCleaner#240]
There is a failure in the spam treatment stage.
Some messages are being tagged, others are being moved to a "where it disappears" quarantine.

EX:
Spam handling stage: 2020-09-22 09:45:21 (5) 887857: message 1kKhfd-000EeN-2v R: <Destination@domain.xyz> S: <From @ orig> status not spam

and:

Spam handling stage: 2020-09-22 09:45:21 (5) 887857: message 1kKhfZ-000EdN-Up R: <Destination@domain.xyz> S: <From @ orig> status not spam

killed in that step

doesn't have: Final outgoing stage:?

**Comment by p-rolle** [comment]
Hi,

We provide direct support to our Enterprise Edition 's customers.
If you are using the Community Edition, we provide a forum where you can find some help and where we help ourselves when our tasks list allows it.
Anyway, here is not the right place to report an issue.

Best regards

**Comment by serpentes80** [comment]
the community is left behind, because there's nothing changing since months now... the problem sill exists!
