### ISSUE TITLE
Spam Qurantine not showing anything! for months now!

### ISSUE THREAD

**Issue by serpentes80** [MailCleaner/MailCleaner#253]
the community is left behind, because there's nothing changing since months now... the problem sill exists!
so don't tell me to post in the forum. because I - and many others did - and nothing changes.

There is a failure in the spam treatment stage.
Some messages are being tagged, others are being moved to a "where it disappears" quarantine.

EX:
Spam handling stage: 2020-09-22 09:45:21 (5) 887857: message 1kKhfd-000EeN-2v R: Destination@domain.xyz S: <From @ orig> status not spam

and:

Spam handling stage: 2020-09-22 09:45:21 (5) 887857: message 1kKhfZ-000EdN-Up R: Destination@domain.xyz S: <From @ orig> status not spam

killed in that step

doesn't have: Final outgoing stage:?

**Comment by p-rolle** [comment]
Hello,

The mail you are referring to is *more than one month old*, we made several changes since then and we currently didnt have such cases for a long time.
If you have a recent case, I would be glad to analyze it but it would require me to be able to investigate on your server. This is why we solve such cases with the Enterprise Edition first : we have access to the server.
If you want to submit such a case, please do it on the dedicated forums.

I can understand that you are unhappy about one point but this is not a reason to tell things that are not true.

The community is not "left behind".
We dont have any big bugs opened "for months".
When we solve an issue for the Enterprise Edition, we solve it for the Community Edition as well as both versions are using the exact same repository.

Best regards,

**Comment by serpentes80** [comment]
for me the problem still exists, although the system is fully patched

Incoming MTA stage: 	2020-10-26 13:14:01 1kX1Nx-000Lo7-7m <= fakeaccount@liebt-die-frau-seines-chefs.de H=(incoming-gw) [xxx.xxx.xxx.xxx] P=esmtp S=5006 DKIM=gmx.net id=trinity-c61eaa0c-6e27-4ad4-ad50-758b250ebf6a-1603714440005@3c-app-gmx-bs71 T="test"
2020-10-26 13:14:01 1kX1Nx-000Lo7-7m => recipient R=filter_forward T=local_smtp S=5102 H=127.0.0.1 [127.0.0.1] C="250 OK id=1kX1Nx-000LoA-AL"
2020-10-26 13:14:01 1kX1Nx-000Lo7-7m Completed
Filtering MTA stage: 	2020-10-26 13:14:01 1kX1Nx-000LoA-AL <= fakeaccount@liebt-die-frau-seines-chefs.de H=(develop-group.de) [127.0.0.1] P=esmtp S=5006 id=trinity-c61eaa0c-6e27-4ad4-ad50-758b250ebf6a-1603714440005@3c-app-gmx-bs71
Filtering Engine: 	Oct 26 13:14:03 localhost MailScanner[61753]: Newsl result is not newsletter (0.0/5.0) for 1kX1Nx-000LoA-AL
Oct 26 13:14:13 localhost MailScanner[61753]: Spamc result is spam (1001.8/5.0) for 1kX1Nx-000LoA-AL
Oct 26 13:14:13 localhost MailScanner[61753]: Message 1kX1Nx-000LoA-AL from xxx.xxx.xxx.xxx (fakeaccount@liebt-die-frau-seines-chefs.de) to <recipientdomain> is spam, Newsl (score=0.0, required=5.0, NONE, position : 0, not decisive), Spamc (score=1001.8, required=5.0, MIME_HTML_ONLY 0.0, DKIM_SIGNED 0.6, DKIM_VALID -0.3, GTUBE 1000, BAYES_50 0.0, HTML_MESSAGE 0.0, RDNS_NONE 1.5, RCVD_IN_MSPIKE_H3 -0.0, RCVD_IN_DNSWL_LOW -0.0, TVD_SPACE_RATIO 0.0, RCVD_IN_MSPIKE_WL -0.0, position : 2, spam decisive)
Oct 26 13:14:13 localhost MailScanner[61753]: Profiled SpamCheck for message 1kX1Nx-000LoA-AL: (Newsl_Check:0.0362s) (Prefilters:9.969s) (SpamCacheCheck:0.0005s) (Spamc_Check:9.8866s) (TrustedSources_Check:0.0451s)
Oct 26 13:14:13 localhost MailScanner[61753]: Spam Actions: message 1kX1Nx-000LoA-AL actions are deliver
Oct 26 13:14:13 localhost MailScanner[61753]: Count updated for 1kX1Nx-000LoA-AL
Oct 26 13:14:13 localhost MailScanner[61753]: Count updated in daemon for 1kX1Nx-000LoA-AL
Outgoing stage: 	2020-10-26 13:14:13 1kX1Nx-000LoA-AL => recipient <recipient> R=filter_checkspam T=spam_store S=5701
2020-10-26 13:14:13 1kX1Nx-000LoA-AL Completed
Spam handling stage: 	2020-10-26 13:14:15 (1) 822328: message 1kX1Nx-000LoA-AL Message will be delivered using SendMeAnyway
2020-10-26 13:14:15 (1) 822328: message 1kX1Nx-000LoA-AL ready to be delivered with new id: 1kX1OB-000Lod-AH
2020-10-26 13:14:15 (1) 822328: message 1kX1Nx-000LoA-AL R:<recipient> S:<fakeaccount@liebt-die-frau-seines-chefs.de> status not spam, module: NOHEADER
Final outgoing stage: 	2020-10-26 13:14:15 1kX1OB-000Lod-AH <= fakeaccount@liebt-die-frau-seines-chefs.de H=(localhost.localdomain) [127.0.0.1] P=esmtp S=5937 id=trinity-c61eaa0c-6e27-4ad4-ad50-758b250ebf6a-1603714440005@3c-app-gmx-bs71
2020-10-26 13:14:15 1kX1OB-000Lod-AH => recipient <recipient> R=filter_checkspam T=spam_store S=5996
2020-10-26 13:14:15 1kX1OB-000Lod-AH Completed****

**Comment by p-rolle** [comment]
Fixed and talked about directly on MailCleaner s Community Edition forums

**Comment by serpentes80** [comment]
> Fixed and talked about directly on MailCleaner s Community Edition forums

wrong!
we don't have a fix, yet!
