### ISSUE TITLE
Temporarily rejected RCPT. Failed to expand ACL string.

### ISSUE THREAD

**Issue by javierwonghf** [MailCleaner/MailCleaner#281]
All of a sudden all mailcleaner instances that we have stopped receiving email and when looking at the incoming MTA logs similar messages like these appear:

`temporarily rejected RCPT <abc@abc.com>: failed to expand ACL string ":after_received:X-MailCleaner-recipients: $recipients": unknown variable name "recipients"`

Any idea how we can overcome this? Thank you.

**Comment by chr1sb** [comment]
To fix this I edited the /usr/mailcleaner/etc/exim/exim_stage1.conf_template, and commented out lines 344, 345 and 346, which appear to have be recently added.

I then ran the /root/Updater4MC/updater4mc.sh script with the git pull lines etc commented out, to restart mailcleaner with the changers to the exim_stage1.con_template file, after this my mailcleaner setup is recieving email again.

**Comment by javierwonghf** [comment]
Thanks real much @chr1sb it worked!! 

Nice workaround till we get something permanent.

**Comment by fundutzi** [comment]
Thank you. Solved it for me.
Forum post with same issue is [here](https://forum.mailcleaner.org/viewtopic.php?f=6&t=3161&p=13019#p13019).

**Comment by reivilob** [comment]
Sorry for this issue
This is now solvet simply do:
/root/Updater4MC/updater4mc.sh
Best regards
Olivier

**Comment by kkloesener** [comment]
The way it is solved is not ideal as it includes ALL BCC addresses in mails. This can be a privacy breach if you use MC as outgoing Relay.
I hope there will be a solution which will work for both scenarios.

Additonally can someone explain the need for this special extra-header?

**Comment by reivilob** [comment]
Hi
this is a temporary roll back to previous situation and we will provide a new patch that solve it
OB

**Comment by juliencluzel07** [comment]
thanks !!

**Comment by gigbuilder** [comment]
fix worked like a charm

**Comment by p-rolle** [comment]
The solution for #248 is currently under tests

**Comment by mdilullo** [comment]
Thanks, it's work great to solve the error.
temporarily rejected RCPT <abc@abc.com>: failed to expand ACL string ":after_received:X-MailCleaner-recipients: $recipients": unknown variable name "recipients"
Great job.

**Comment by p-rolle** [comment]
As mentionned by reivilob  this was fixed 6 days ago.

**Comment by javierwonghf** [comment]
Thanks so much guys for solving this. Much appreciated.
