### ISSUE TITLE
bl.spamcop.net positive false problem

### ISSUE THREAD

**Issue by pottendir** [MailCleaner/MailCleaner#295]
Dear Developers,

from today noon there is a problem with bl.spamcop.net RBL list. It provides false positive almost of all IP address. It tried to switch off this list in the PreRBL and Spamc part of Anti-Spam menu, It looks like it was successful but all the same and the Mailcleaner reject the incoming mails because of bl.spamcop.net . How can I remove this RBL list manually?

I restarted the FIlter Engine after the modification.

Thanks in advance!
Robert

**Comment by p-rolle** [comment]
Hello,
This issue was covered in our Community Edition forum. This issue is not due to MailCleaner.
You probably wanted to disable this RBL from Configuration->SMTP web interface.
However, the issue is fixed by now.
best regards,
