### ISSUE TITLE
All incoming IPv6 SMTP connections dropped with "550 Administrative prohibition"

### ISSUE THREAD

**Issue by dam2k** [MailCleaner/MailCleaner#310]

**Comment by dam2k** [comment]
Hi.
From tonight, any incoming SMTP connection are dropped with 550 Administrative prohibition.
The /var/mailcleaner/log/exim_stage1/mainlog lg reports:
2021-02-23 13:25:17 H=mail-lj1-x22f.google.com [2a00:1450:4864:20::22f] rejected connection in "connect" ACL

Never had this problem before. Also we did not change anything. 
Thank you.

**Comment by goodomens42** [comment]
Same problem here ...

**Comment by andersonvaz** [comment]
Same problem here ...

**Comment by goodomens42** [comment]
[juergen@termsrv03 ~]$ telnet -6 mx01.MYDOMAIN.de 25
Trying 2a01:4f8:affe:cafe::134...
Connected to mx01.MYDOMAIN.de.
Escape character is '^]'.
550 Administrative prohibition
Connection closed by foreign host.

No idea how to fix this.
IPv6 is crucial for our deployment

**Comment by andersonvaz** [comment]
I have problem in IPV4 too

telnet mailc3.deploycloud.com.br 25
Trying 198.204.254.172...
Connected to mailc3.deploycloud.com.br.
Escape character is '^]'.
550 Administrative prohibition
Connection closed by foreign host.

**Comment by andersonvaz** [comment]
After the update and reboot it worked correctly

/root/Updater4MC/updater4mc.sh

**Comment by dam2k** [comment]
Me too. After a manual update the error is gone and IPv6 is working as expected.
Thank you.

**Comment by p-rolle** [comment]
Hello,
as soon as this was fixed, I mentioned to run /root/Updater4MC/updater4mc.sh in a dedicated post in MailCleaner Community Edition forums. Please open an account on those forums to be updated ASAP in case of such problems
