### ISSUE TITLE
Cant send any mail after upgrade

### ISSUE THREAD

**Issue by pkejval** [MailCleaner/MailCleaner#344]
After upgrading Exim to new version every outgoing mail is stuck in spooler with this error:

R=copyto_route defer (-1): failed to expand "${if and{ {!eq {$sender_address}{}} {or {{eq {$acl_c0}{relayed}} {eq {$acl_c1}{authenticated}} }}{exists{/var/mailcleaner/spool/tmp/exim_stage1/copyto/${sender_address_domain}}} }{${lookup{$sender_address_local_part}nwildlsearch{/var/mailcleaner/spool/tmp/exim_stage1/copyto/${sender_address_domain}}}} {} }": NULL

**Comment by pkejval** [comment]
Temporary fixed with editing exim_stage1.conf_template_4.94 line 1067

section "copyto_route"
data = archive@domain.tld

I'm sorry I'm unable to post PR because I'm not familiar with MC templating system. I just posting this quick fix to another admins with broken MC.

**Comment by JohnMertz** [comment]
Hello,

I'm working on a patch for this right now.

If I understand correctly you just replaced it with a static string?

It's not so much our templating system as Exim's configuration format. Our templates just get dumped with `__VARIABLES__` replaced and with conditional sections removed. Exim changed how it regulates 'tainted' paths (paths that are built using user input variables). So the solution is to get an untainted value for `${sender_address_domain}`.

If anyone else sees this and they cannot simply replace with a static value, you can revert to the previous version of Exim until a solution is published.

  apt-get install mc-exim=4.92.3

The dumper will select the correct template depending on which version is installed, so when Exim is restarted, it will load your templates from prior to last night's upgrade.

**Comment by pkejval** [comment]
Exactly. I replaced template string with static string as workaround.

**Comment by JohnMertz** [comment]
This issue and others opened in Enterprise support should be resolved by #345, pending review and merge, but it is currently in place successfully on our Cloud and several clients.

@pkejval, You could checkout the PR if you would like to test it, otherwise the PR should be merged in the morning (Swiss time) and you can reset your template, pull the repository and restart exim_stage1
