### ISSUE TITLE
Newslist + Whitelist from spam quarantine broken

### ISSUE THREAD

**Issue by Chrisc-c-c** [MailCleaner/MailCleaner#355]
After the latest commit (https://github.com/MailCleaner/MailCleaner/commit/855bae22d239116249b0a4b9481712ff70a1b70d) whitelisting for both spam and newsletters from the block page is now broken.

![image](https://user-images.githubusercontent.com/18648720/123343318-6f34eb00-d549-11eb-9ccd-f35adc99296c.png)

Clicking on Newlist works fine, but clicking "Newslist + Whitelist" returns an HTTP 500 error.

Looking in system logs, I can see this is failing with ` localhost httpd: PHP Fatal error:  Call to undefined function extractSender() in /usr/mailcleaner/www/user/htdocs/newswhitelist.php on line 132`

Looking at the source of the file, It appears an include is missing for utils.php which contains the missing function.

**Comment by Chrisc-c-c** [comment]
I've submitted a pull request to fix this missing include. This resolves the HTTP 500 error, but I now receive the following message when clicking the button:

![image](https://user-images.githubusercontent.com/18648720/123344049-f2a30c00-d54a-11eb-86a1-42f127b44ff5.png)

So it seems these changes may have introduced other bugs.

**Comment by reivilob** [comment]
Thanks a lot for this contribution, we will investigate if this error message is another bug, or if this is just due to an already existing entry in the whitelist database ...
