### ISSUE TITLE
mailcleaner_cron.pl error messages: md5sum: clamav-83dc25e2d8d05b4693db404fcdb5e9b5.tmp: Is a directory

### ISSUE THREAD

**Issue by cliffalbert** [MailCleaner/MailCleaner#365]
mailcleaner_cron.pl sometimes starts reporting errors due to an issue in bin/fetch_clamav.sh

md5sum: clamav-83dc25e2d8d05b4693db404fcdb5e9b5.tmp: Is a directory

This can be fixed by altering line 96 in bin/fetch_clamav.sh from:

if [ -e "$VARDIR/spool/tmp/clamav/$file" ]; then

to

if [ -f "$VARDIR/spool/tmp/clamav/$file" ]; then

Ofcourse the real problem is why are there directories created ?

**Comment by JohnMertz** [comment]
Hello,

This should have been fixed by #367 

-John
