### ISSUE TITLE
dump_firewall.pl does not take the protocol as a key to build etc/firewall/start

### ISSUE THREAD

**Issue by fsoyer** [MailCleaner/MailCleaner#368]
Hi,
trying to add a rule for udp+tcp on the same port in mailcleaner firewall, I added two lines in the table external_access, one for each protocol, same service and same IP (0.0.0.0/0). But when I did a firewall restart, only the last line was kept. I've found that the key "$description" of the 2-dimensional array "%rules" in dump_firewall.pl is build only on host+port, so the last line host+port overwrites the preceding ones, no matter the protocol.
Is this a requirement or just an oversight ? Can this introduces a bug if we add the protocol in the key of %rules ?
Or maybe, there is another way to do this, and I haven't found it...
Thank you for your opinions.

**Comment by fsoyer** [comment]
Hi guys,
any idea about this ? Please take a moment for viewing this, I'm actually blocked because I don't want to modify anything without your opinion. Thanks.

**Comment by fsoyer** [comment]
I've added a pull request #412  for this.

**Comment by JohnMertz** [comment]
Sorry that no one appears to have taken on this issue. I was working on [a mostly unrelated patch](#434) to the firewall dumper when I noticed your issue. Your commit is duplicated there.
