### ISSUE TITLE
Can't receive any external email after yesterday upgrade

### ISSUE THREAD

**Issue by quakeice** [MailCleaner/MailCleaner#415]
We are not able to receive mail from outside. Every mail is blocked in Filtering Spool and nothing goes into outgoing spool.
Anyone can help me please?
Thanks in advance

**Comment by reivilob** [comment]
Hi
please use the forum.mailcleaner.org for assistance regarding MailCleaner Community Edition 
A topic is open regarding this issue
OB

**Comment by quakeice** [comment]
Thank you JohnMertz for your advices.
Automatic update didn't work because there was a lock file...
now it's working propertly.
Have a nice day.
Giacomo
