### ISSUE TITLE
Problem with "Monitoring - Status"

### ISSUE THREAD

**Issue by hasz78** [MailCleaner/MailCleaner#419]
Hi
I have problem with this after upgrade some ago time.

`Nov 30 22:54:32 localhost httpd: PHP Warning:  Invalid argument supplied for foreach() in /usr/mailcleaner/www/guis/admin/public/templates/default/scripts/ajax/monitorstatus/hoststatus.phtml on line 80
Nov 30 22:54:32 localhost httpd: PHP Warning:  Illegal string offset 'memtotal' in /usr/mailcleaner/www/guis/admin/public/templates/default/scripts/ajax/monitorstatus/hoststatus.phtml on line 104
Nov 30 22:54:32 localhost httpd: PHP Warning:  Division by zero in /usr/mailcleaner/www/guis/admin/public/templates/default/scripts/ajax/monitorstatus/hoststatus.phtml on line 104
Nov 30 22:54:32 localhost httpd: PHP Warning:  Illegal string offset 'memused' in /usr/mailcleaner/www/guis/admin/public/templates/default/scripts/ajax/monitorstatus/hoststatus.phtml on line 104
Nov 30 22:54:32 localhost httpd: PHP Warning:  Illegal string offset 'memcached' in /usr/mailcleaner/www/guis/admin/public/templates/default/scripts/ajax/monitorstatus/hoststatus.phtml on line 104
Nov 30 22:54:32 localhost httpd: PHP Warning:  Illegal string offset 'exim_stage1' in /usr/mailcleaner/www/guis/admin/public/templates/default/scripts/ajax/monitorstatus/hoststatus.phtml on line 187
Nov 30 22:54:32 localhost httpd: PHP Warning:  Illegal string offset 'exim_stage2' in /usr/mailcleaner/www/guis/admin/public/templates/default/scripts/ajax/monitorstatus/hoststatus.phtml on line 187
Nov 30 22:54:32 localhost httpd: PHP Warning:  Illegal string offset 'exim_stage4' in /usr/mailcleaner/www/guis/admin/public/templates/default/scripts/ajax/monitorstatus/hoststatus.phtml on line 187
Nov 30 22:54:32 localhost httpd: PHP Warning:  Illegal string offset 'apache' in /usr/mailcleaner/www/guis/admin/public/templates/default/scripts/ajax/monitorstatus/hoststatus.phtml on line 187
Nov 30 22:54:32 localhost httpd: PHP Warning:  Illegal string offset 'mailscanner' in /usr/mailcleaner/www/guis/admin/public/templates/default/scripts/ajax/monitorstatus/hoststatus.phtml on line 187
Nov 30 22:54:32 localhost httpd: PHP Warning:  Illegal string offset 'mysql_master' in /usr/mailcleaner/www/guis/admin/public/templates/default/scripts/ajax/monitorstatus/hoststatus.phtml on line 187
Nov 30 22:54:32 localhost httpd: PHP Warning:  Illegal string offset 'mysql_slave' in /usr/mailcleaner/www/guis/admin/public/templates/default/scripts/ajax/monitorstatus/hoststatus.phtml on line 187
Nov 30 22:54:32 localhost httpd: PHP Warning:  Illegal string offset 'snmpd' in /usr/mailcleaner/www/guis/admin/public/templates/default/scripts/ajax/monitorstatus/hoststatus.phtml on line 187
Nov 30 22:54:32 localhost httpd: PHP Warning:  Illegal string offset 'greylistd' in /usr/mailcleaner/www/guis/admin/public/templates/default/scripts/ajax/monitorstatus/hoststatus.phtml on line 187
Nov 30 22:54:32 localhost httpd: PHP Warning:  Illegal string offset 'cron' in /usr/mailcleaner/www/guis/admin/public/templates/default/scripts/ajax/monitorstatus/hoststatus.phtml on line 187
Nov 30 22:54:32 localhost httpd: PHP Warning:  Illegal string offset 'preftdaemon' in /usr/mailcleaner/www/guis/admin/public/templates/default/scripts/ajax/monitorstatus/hoststatus.phtml on line 187
Nov 30 22:54:32 localhost httpd: PHP Warning:  Illegal string offset 'spamd' in /usr/mailcleaner/www/guis/admin/public/templates/default/scripts/ajax/monitorstatus/hoststatus.phtml on line 187
Nov 30 22:54:32 localhost httpd: PHP Warning:  Illegal string offset 'clamd' in /usr/mailcleaner/www/guis/admin/public/templates/default/scripts/ajax/monitorstatus/hoststatus.phtml on line 187
Nov 30 22:54:32 localhost httpd: PHP Warning:  Illegal string offset 'clamspamd' in /usr/mailcleaner/www/guis/admin/public/templates/default/scripts/ajax/monitorstatus/hoststatus.phtml on line 187
Nov 30 22:54:32 localhost httpd: PHP Warning:  Illegal string offset 'spamhandler' in /usr/mailcleaner/www/guis/admin/public/templates/default/scripts/ajax/monitorstatus/hoststatus.phtml on line 187
Nov 30 22:54:32 localhost httpd: PHP Warning:  Illegal string offset 'newsld' in /usr/mailcleaner/www/guis/admin/public/templates/default/scripts/ajax/monitorstatus/hoststatus.phtml on line 187
Nov 30 22:54:32 localhost httpd: PHP Warning:  Illegal string offset 'firewall' in /usr/mailcleaner/www/guis/admin/public/templates/default/scripts/ajax/monitorstatus/hoststatus.phtml on line 187
`
![image](https://user-images.githubusercontent.com/81359379/144134146-c8720d84-2a8d-4644-a642-cfc022dc0ad0.png)

thanks for advice

**Comment by JohnMertz** [comment]
Hello,

I have not been able to replicate this issue.

From the best that I can tell, this suggests that the call at line 12 of the file mentioned:

```
     $status = $this->slave->getStatusValues();
```

is unsuccessfully fetching the values which are then resulting in the errors upon being called. eg.

```
foreach ($status['disksusage'] as $disk) {
```

named the as the first error at line 80. This function is defined in '/usr/mailcleaner/www/guis/admin/application/models/Slave.php', so my best suggestion would be to try to insert some debugging code in that file to dump what values have be found at various places in the function.

Without being able to replicate the issue, it is difficult for us to make other suggestions.

If you were to register for an Enterprise trial our support keys will be installed to allow us remote access and you could make a formal support request.

-John

**Comment by rafaelsupport** [comment]
hey guys
how can i restart "incoming MTA" using command line instead web interface?
i saw this script "/usr/mailcleaner/bin/get_status.pl" to get status and it works fine, even though I don't understand anything about perl
but i would like to know how to manage exim_stage1 (incoming MTA) in command line. stop, start and restart

**Comment by JohnMertz** [comment]
All services are managed using the init files in `/usr/mailcleaner/etc/init.d/`. eg:

```
/usr/mailcleaner/etc/init.d/exim_stage1 restart
```

**Comment by JohnMertz** [comment]
Cannot replicate and no further comments on main issue. Closing.
