### ISSUE TITLE
No more header mail details in tracing

### ISSUE THREAD

**Issue by troublestarter** [MailCleaner/MailCleaner#420]
Hi,

I just saw that we have no more header status in tracing section

![image](https://user-images.githubusercontent.com/6012203/144633647-ec67e506-fcb3-44f7-8cca-0cff5d15a80c.png)

You must put the mouse on the date/time to have ip sources informations etc.

![image](https://user-images.githubusercontent.com/6012203/144633739-e6441ffe-d463-44db-9bac-b16b409cb7d2.png)

Is it possible to fix this ?

Thanks you

Forum : https://forum.mailcleaner.org/viewtopic.php?f=2&t=3278&p=13438#p13438

**Comment by troublestarter** [comment]
Confirmed by other user 
![image](https://user-images.githubusercontent.com/6012203/144639049-124636cf-7a79-4c42-823c-b9bfbf75157f.png)

**Comment by JohnMertz** [comment]
Hello,

If I understand you correctly, you are saying that the headings (and columns) that are visible are the only ones presented. In other words there are no columns for:

Recipients | Spam status | Content status | Deliver status | Delivery date

If this is as I describe, I think I know the commit responsible.

Currently everything works on the machines I've tried, but that may be a difference in the returned logs for my queries.

I just need your confirmation so that I can try to replicate the issue. Thanks.

**Comment by troublestarter** [comment]
Not sure you understood, i will ltry to explain better :

Here i the full screenshot 
![image](https://user-images.githubusercontent.com/6012203/144676669-a9980799-6354-4abe-b820-39c81a65c5cc.png)

The mail headers (header info) are not exsiting anymore, look at my red rectangle

Thanks you

**Comment by viatatec** [comment]
same problem, any tip?

**Comment by Brauadler** [comment]
> Confirmed by other user ![image](https://user-images.githubusercontent.com/6012203/144639049-124636cf-7a79-4c42-823c-b9bfbf75157f.png)

The last commit (ff75a00) solved my problem. The mail specific informations from the different logs are back in the tracing section.

Thanks for solving.

**Comment by viatatec** [comment]
> > Confirmed by other user ![image](https://user-images.githubusercontent.com/6012203/144639049-124636cf-7a79-4c42-823c-b9bfbf75157f.png)
> 
> The last commit ([ff75a00](https://github.com/MailCleaner/MailCleaner/commit/ff75a00eadd4adfe1e87a7cf9770252bf129690a)) solved my problem. The mail specific informations from the different logs are back in the tracing section.
> 
> Thanks for solving.

solved thanks

**Comment by troublestarter** [comment]
> > > Confirmed by other user ![image](https://user-images.githubusercontent.com/6012203/144639049-124636cf-7a79-4c42-823c-b9bfbf75157f.png)
> > 
> > 
> > The last commit ([ff75a00](https://github.com/MailCleaner/MailCleaner/commit/ff75a00eadd4adfe1e87a7cf9770252bf129690a)) solved my problem. The mail specific informations from the different logs are back in the tracing section.
> > Thanks for solving.
> 
> solved thanks

Can you just confirm me how to install the commit please ?

**Comment by viatatec** [comment]
> > > > Confirmed by other user ![image](https://user-images.githubusercontent.com/6012203/144639049-124636cf-7a79-4c42-823c-b9bfbf75157f.png)
> > > 
> > > 
> > > The last commit ([ff75a00](https://github.com/MailCleaner/MailCleaner/commit/ff75a00eadd4adfe1e87a7cf9770252bf129690a)) solved my problem. The mail specific informations from the different logs are back in the tracing section.
> > > Thanks for solving.
> > 
> > 
> > solved thanks
> 
> Can you just confirm me how to install the commit please ?

Just edit the file: /opt/mailcleaner/bin/search_log.pl and delete the "unlink($fullogfile);" at line 222

**Comment by Brauadler** [comment]
@troublestarter  You can start the updater4mc.sh manually on your server or wait until the cronjob starts it by itself at midnight

**Comment by troublestarter** [comment]
The commit is already in "master" branch ?

I will try this : Just edit the file: /opt/mailcleaner/bin/search_log.pl and delete the "unlink($fullogfile);" at line 222

**Comment by JohnMertz** [comment]
As mentioned, the commit that removed the above 'unlink' line resolved the issue. The file should not be manually edited as this could introduce a conflict which blocks future updates. Nor is it necessary to run the full Updater4MC script since it is only the one file that is changed, not any other system components. You can just pull the git tree:

```
cd /usr/mailcleaner; git pull
```
