### ISSUE TITLE
SMTP Page "Application Error" on latest update

### ISSUE THREAD

**Issue by moh30ly** [MailCleaner/MailCleaner#428]
After updating Mailcleaner to latest release, I keep getting error on the SMTP Page 

GET https://mailcleaner.rubixgrid.com/admin/smtp/smtpchecks 500 (Internal Server Error)
If I try to update from the terminal I get the following errors 

`root@mailcleaner:~/.pyenv# /root/Updater4MC/updater4mc.sh
2022-02-03_14:57:02 Launching Updater4MC
HEAD is now at e3089eb Merge pull request #50 from JohnMertz/watchdog_cron
Your branch is up-to-date with 'origin/master'.
No local changes to save
Already up-to-date.
NoChanges: Nothing to do
Importing library: /root/Updater4MC/libs/apt-install.lib ...Done.
Importing library: /root/Updater4MC/libs/check_db_schema.lib ...Done.
Importing library: /root/Updater4MC/libs/utils_import.lib ...Done.
Importing library: /root/Updater4MC/libs/version.lib ...Done.
Already updated: /root/Updater4MC/updates/01_httpsgit.update ...
Already updated: /root/Updater4MC/updates/02_mcgitupdate.update ...
Already updated: /root/Updater4MC/updates/03_instperllibs.update ...
Already updated: /root/Updater4MC/updates/04_spamc-dns-patch_bayes-rights.update ...
Already updated: /root/Updater4MC/updates/05_updater-flagfile.update ...
Already updated: /root/Updater4MC/updates/06_exim-upgrade.update ...
Already updated: /root/Updater4MC/updates/07_fix-exim-and-update-version.update ...
Already updated: /root/Updater4MC/updates/08_update-version.update ...
Already updated: /root/Updater4MC/updates/09_unique-wwlist-key.update ...
Already updated: /root/Updater4MC/updates/10_userpref_lang_size.update ...
Already updated: /root/Updater4MC/updates/11_kaspersky_init.update ...
Already updated: /root/Updater4MC/updates/12_tnef_fix.update ...
Already updated: /root/Updater4MC/updates/13_update-version.update ...
Already updated: /root/Updater4MC/updates/14_internal-access-setup.update ...
Already updated: /root/Updater4MC/updates/15_internal-access-setup-bis.update ...
Already updated: /root/Updater4MC/updates/16_update_wget_ca_certificate.update ...
Already updated: /root/Updater4MC/updates/17_whitelist_for_password_protected_archives.update ...
Already updated: /root/Updater4MC/updates/18_internal-access-keys.update ...
Already updated: /root/Updater4MC/updates/19_address_group_for_ldap.update ...
Already updated: /root/Updater4MC/updates/20_SPF_DMARC_Exception_field.update ...
Already updated: /root/Updater4MC/updates/21_ClamAV_101.update ...
Already updated: /root/Updater4MC/updates/22_ClamAV_101_2.update ...
Already updated: /root/Updater4MC/updates/23_mc_exim_4_92.update ...
Already updated: /root/Updater4MC/updates/24_mc_exim_4_92_2.update ...
Already updated: /root/Updater4MC/updates/25_mc_exim_4_92_3.update ...
Already updated: /root/Updater4MC/updates/26_mc_clamav_0.101.4.update ...
Already updated: /root/Updater4MC/updates/27_lots_of_money_improved.update ...
Already updated: /root/Updater4MC/updates/28_adapt_mailscanner_regex_for_new_exim.update ...
Already updated: /root/Updater4MC/updates/29_mc_exim_4_93_0_4.update ...
Already updated: /root/Updater4MC/updates/30_mc_exim_4_92_.update ...
Already updated: /root/Updater4MC/updates/31_whitelist_mc_newsletter.update ...
Already updated: /root/Updater4MC/updates/32_MailScanner_patch_HTML_Controls_wl.update ...
Already updated: /root/Updater4MC/updates/33_default_SMTP_ciphers.update ...
Already updated: /root/Updater4MC/updates/34_Pyenv-library-install-3-7-7.update ...
Already updated: /root/Updater4MC/updates/35_forcewatchdog_update.update ...
Already updated: /root/Updater4MC/updates/36_razor2_fix.update ...
Already updated: /root/Updater4MC/updates/37_change_Updater4mc_time.update ...
Already updated: /root/Updater4MC/updates/38_change_Updater4mc_time.update ...
Already updated: /root/Updater4MC/updates/39_fail2ban_install.update ...
Already updated: /root/Updater4MC/updates/40_relay_summary_dependency.update ...
Already updated: /root/Updater4MC/updates/41_update_fail2ban.update ...
Executing update: /root/Updater4MC/updates/42_remove_SH_zen_RBL.update ...
GZip perl dependencies for relay summary script
rm: cannot remove ‘etc/rbls/SPAMHAUS.cf’: No such file or directory
End of update.
Already updated: /root/Updater4MC/updates/43_force_stage1_template_reset.update ...
Already updated: /root/Updater4MC/updates/44_full_whitelist.update ...
Already updated: /root/Updater4MC/updates/45_spamhaus.update ...
Already updated: /root/Updater4MC/updates/46_surbl.update ...
Already updated: /root/Updater4MC/updates/47_Newsl_Lg_removal.update ...
Already updated: /root/Updater4MC/updates/48_Newsl_All_Lg_removal.update ...
Already updated: /root/Updater4MC/updates/49_Remove_old_SH_rules.update ...
Already updated: /root/Updater4MC/updates/50_fail2ban_fix.update ...
Already updated: /root/Updater4MC/updates/51_prevent_double_spam_entries.update ...
Already updated: /root/Updater4MC/updates/52_disable_nocaps.update ...
Already updated: /root/Updater4MC/updates/53_MailScanner_patch_HTML_Controls_wl_ip.update ...
Already updated: /root/Updater4MC/updates/54_Whitelist_first.update ...
Already updated: /root/Updater4MC/updates/55_SpamC_Ajustment.update ...
Already updated: /root/Updater4MC/updates/55_Validate_IP_Library.update ...
Already updated: /root/Updater4MC/updates/56_fail2ban_default_chain.update ...
Already updated: /root/Updater4MC/updates/57_Switch_Library.update ...
Already updated: /root/Updater4MC/updates/58_swaks_install.update ...
Already updated: /root/Updater4MC/updates/59_MailScanner_patch_hide_scripts.update ...
Already updated: /root/Updater4MC/updates/60_MailScanner_patch_hide_scripts2.update ...
Already updated: /root/Updater4MC/updates/61_int128_lib.update ...
Already updated: /root/Updater4MC/updates/62_mc_exim_4.94.update ...
Already updated: /root/Updater4MC/updates/63_disable_tcp_scaling.update ...
Already updated: /root/Updater4MC/updates/64_content_checkmark.update ...
Already updated: /root/Updater4MC/updates/65_pyenv_fix.update ...
Already updated: /root/Updater4MC/updates/66_bashrc_file.update ...
Executing update: /root/Updater4MC/updates/67_pyenv_upgrade.update ...
-su: line 0: cd: /var/mailcleaner/.pyenv: No such file or directory
fatal: Not a git repository (or any parent up to mount point /var)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
not in branch master... Fixing
-su: line 0: cd: /var/mailcleaner/.pyenv: No such file or directory
fatal: Not a git repository (or any parent up to mount point /var)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
-su: line 0: cd: /var/mailcleaner/.pyenv: No such file or directory
fatal: Not a git repository (or any parent up to mount point /var)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /var)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
        Error during /root/Updater4MC/updates/67_pyenv_upgrade.update update. Please join logfile to your post on MailCleaner Community forum.`

![image](https://user-images.githubusercontent.com/81865299/152420713-eb2f8d63-3795-4121-b456-dbfcf2ce30a0.png)

**Comment by moh30ly** [comment]
Solution was posted by th user madhopsman here https://forum.mailcleaner.org/viewtopic.php?f=16&t=3292

I was having the exact same problem. For those seeing this as well, here's more succinct instructions on how to fix:
Log in to your server via ssh or console as root
open /usr/mailcleaner/install/install_pyenv_3-7-7.sh in your favorite editor.
Edit line 51 in the script from
CODE: [SELECT ALL](https://forum.mailcleaner.org/viewtopic.php?f=16&t=3292#)

export PYENV_ROOT="$HOME/.pyenv"
to
CODE: [SELECT ALL](https://forum.mailcleaner.org/viewtopic.php?f=16&t=3292#)

export PYENV_ROOT="$VARDIR/.pyenv"
Edit line 60 from
CODE: [SELECT ALL](https://forum.mailcleaner.org/viewtopic.php?f=16&t=3292#)

if [ SSL_VERSION -ne "OpenSSL 1.1.1g 21 Apr 2020" ]
to
CODE: [SELECT ALL](https://forum.mailcleaner.org/viewtopic.php?f=16&t=3292#)

if [ "$SSL_VERSION" != "OpenSSL 1.1.1g  21 Apr 2020".  ]
Note the extra space after 1.1.1g here.
Execute the script:
CODE: [SELECT ALL](https://forum.mailcleaner.org/viewtopic.php?f=16&t=3292#)

/usr/mailcleaner/install/install_pyenv_3-7-7.sh
Run
CODE: [SELECT ALL](https://forum.mailcleaner.org/viewtopic.php?f=16&t=3292#)

chown mailcleaner:mailcleaner /var/mailcleaner/.pyenv -R
If you get an error about /var/mailcleaner/.pyenv already existing, just rename it and run again. Once the above is done, you should be able to complete the update via updater4mc.sh

**Comment by JooJooBee666** [comment]
This probably should NOT have been closed.  The script needs to be fixed.  How do I reopen?
