### ISSUE TITLE
Fail2ban doesn't load all jails after reboot

### ISSUE THREAD

**Issue by bogdankruszewski** [MailCleaner/MailCleaner#455]
Referencing #450 
With these changes Fail2ban doesn't load all jails after reboot.

Only empty fail2ban-default, fail2ban-mc-exim, fail2ban-mc-ssh  and fail2ban-mc-webauth  jails are created in iptables.

If I restart the firewall again after a reboot with `/usr/mailcleaner/etc/init.d/firewall restart` the following correct jails will be created according to my configuration: fail2ban-mc-exim, fail2ban-mc-exim-bl, fail2ban-mc-ssh, fail2ban-mc-ssh-bl, fail2ban-mc-webauth and fail2ban-mc-webauth-bl. All blacklist jails will also be correctly populated with blacklisted IPs.

I suppose that at the stange of the changes in #450 the slave database is not ready yet, therefore no individual configuration will be loaded, but only the defaults. This can cause duplicated IP problems in fail2ban_ips MySQL tables, which can cause issues with freezing the F2B service completely. I've already had these issues and after I've removed duplicated IPs from the MySQL table and started the F2B service via systemctl after the mailcleaner service, everything has worked. Now I've reverted my previous changes, but probably the issues can start again, if the correct jails are not populated at a reboot.

@JohnMertz, is there a possibility to check in #450, if the DB (master and slave) is running and in sync, before starting or reloading the firewall settings?

**Comment by JohnMertz** [comment]
Many changes have been made to fail2ban since this issue was created. I'm currently unable to replicate this problem as things stand on my personal server. I'm going to close the issue, but if you still have problems, feel free to open a new one.
