### ISSUE TITLE
cdnmcpool.mailcleaner.net 403

### ISSUE THREAD

**Issue by sergioadofaci** [MailCleaner/MailCleaner#490]
Hello,

When trying to run apt update  I get this error:

      "Err http://cdnmcpool.mailcleaner.net jessie/main amd64 Packages",
        "  403  Forbidden"

Am I the only one?

Thanks!.

**Comment by JohnMertz** [comment]
We are in the process of migrating our CDN provider. We will investigate this issue and let you know when it is resolved.

**Comment by reivilob** [comment]
It should be solved now, a small mistake on the new CDN configuration
