### ISSUE TITLE
Error_reporting in SmtpChecks.php shows Notice

### ISSUE THREAD

**Issue by Brauadler** [MailCleaner/MailCleaner#493]
Hello,

after the activation of error_reporting in #[734f6e6](https://github.com/MailCleaner/MailCleaner/commit/734f6e6bb5f1fdd766aca45395f34babb84002a4) SmtpChecks.php, there is an Notice with Undefinded Index: REGISTERED. The notice is too big for the column and so the first column is compressed and the layout is changed strangely. 

Since I can't understand the reason for active Error_Reporting in this file, is it possible to fix the error or configure reporting without E_Notice?

![grafik](https://user-images.githubusercontent.com/95625809/190320090-e7835379-0588-422c-bb4b-40c4ebd6a460.png)
![grafik](https://user-images.githubusercontent.com/95625809/190320177-455e8d62-b23e-45e8-aad5-c9b8e6f33f2e.png)

**Comment by JohnMertz** [comment]
The reporting configuration was mastakenly left in to the last update when the last setting on that page was being added. I'll remove it and also fix the error that caused the output to appear in the first place. Thanks for pointing this out.

**Comment by JohnMertz** [comment]
Resolved by #494
