### ISSUE TITLE
Error to test spamC custom rule

### ISSUE THREAD

**Issue by rafaelsupport** [MailCleaner/MailCleaner#496]
Looking this tutorial: https://support.mailcleaner.net/boards/3/topics/51-how-to-create-custom-spamc-rules I made a custom rule using a file called: `99_custom_rules_contents.cf` at `/usr/mailcleaner/share/spamassassin`

```
body RULE_BLOCKCONTENTS_01 /valid your account/
score RULE_BLOCKCONTENTS_01 2
```

When I run this test `/usr/local/bin/spamassassin -p 99_custom_rules_contents.cf < email`, I get the result expected: 

```
[....]
X-Spam-Flag: YES
X-Spam-Level: *****
X-Spam-Status: Yes, [....]
```
But when I run the second test: `/usr/local/bin/spamassassin --siteconfigpath=/usr/mailcleaner/share/spamassassin/ -t -d < email`, I get some warnings and **X-Spam-Flag** not get "**YES**":

```
Sep 19 10:14:21.227 [20499] warn: plugin: failed to parse plugin /usr/mailcleaner/share/spamassassin/plugins/FuzzyOcr.pm: "salog" is not exported by the FuzzyOcr::Logging module
Sep 19 10:14:21.227 [20499] warn: Can't continue after import errors at /usr/mailcleaner/share/spamassassin/plugins/FuzzyOcr.pm line 70.
Sep 19 10:14:21.227 [20499] warn: BEGIN failed--compilation aborted at /usr/mailcleaner/share/spamassassin/plugins/FuzzyOcr.pm line 70.
Sep 19 10:14:21.227 [20499] warn: Compilation failed in require at /usr/local/share/perl/5.20.2/Mail/SpamAssassin/PluginHandler.pm line 109.
Sep 19 10:14:21.784 [20499] warn: Number found where operator expected at (eval 1896) line 1, near "2 0"
Sep 19 10:14:21.784 [20499] warn:  (Missing operator before 0?)
X-Spam-Checker-Version: SpamAssassin 3.4.0 (2014-02-07) on mailcleaner
X-Spam-Level: ****
X-Spam-Status: No, [...]
```

In a real test send an email, this email is not detected as spam
How can I fix this?

**Comment by JohnMertz** [comment]
First, the same rule works on my stock installation (if 'valid your account' is actually in the email being tested). This tells me that the plugin warning message indicates that something is breaking before actually getting to the scan. This would be something that exists within the remainder of the SpamAssassin configuration directory.

I see the FuzzyOcr errors on my machine, but I don't have the PluginHandler one.

Immediately prior to line 109 it should output which plugin it is trying to load if you include the `-D` debug flag like `plugin: loading $package from $path`. This will hopefully tell you which plugin is causing the problem. It may also show some other error.
