### ISSUE TITLE
Mailcleaner not received mails

### ISSUE THREAD

**Issue by mafer0410** [MailCleaner/MailCleaner#497]
Mailcleaner not received mails. 
In logs appears:
(SSL_CTX_use_certificate_chain_file file=/var/mailcleaner/spool/tmp/exim/certificate): error:02001002:system library:fopen:No such file or directory

**Comment by JohnMertz** [comment]
The file at that location should be created by `/usr/mailcleaner/bin/dump_exim.pl 1` or `4`. It pulls the certicate that you have installed at Configuration->SMTP->TLS/SSL and dumps it to that file each time one of the edge MTAs restarts. The error indicates that either there is an error, which you should see if you run the script manually, or you have no certificate (but have SSL enabled anyways).

**Comment by mafer0410** [comment]
Thanks for the help.
