### ISSUE TITLE
mailcleaner haproxy

### ISSUE THREAD

**Issue by troublestarter** [MailCleaner/MailCleaner#504]
Hello

Fail2ban ban my internal IP of haproxy in mc-webauth jail.
apache in mailcleaner can't see real ip source even if i pass X-Forwarded-For headers.

In standard apache configuration, it is simple to add this to have real IP to be logged :
a2enmod remoteip
echo "RemoteIPHeader X-Forwarded-For" > /etc/apache2/conf-available/haproxyIP.conf
a2enconf haproxyIP
systemctl reload apache2

Is it possible to make apache in mailcleaner to activate this to support X-Forwarded-For headers ?

Thanks you.

**Comment by helpquick** [comment]
You could acheive this by adding /usr/mailcleaner/etc/apache/sites/ha_proxy.conf

```
LoadModule remoteip_module modules/mod_remoteip.so
RemoteIPInternalProxy x.x.x.x
RemoteIPHeader X-Forwarded-For
RemoteIPHeader X-Real-IP
LogFormat "%a %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" [pid %P]" combined

```
and restart apache:
`/usr/mailcleaner/etc/init.d/apache restart`

The above config is what I use to put my webservers behind an NGINX proxy.

I have it in place on mine, and works fine.

**Comment by troublestarter** [comment]
With HAPROXy works without "RemoteIPHeader X-Real-IP"

So i use now :

LoadModule remoteip_module modules/mod_remoteip.so
RemoteIPInternalProxy x.x.x.x
RemoteIPHeader X-Forwarded-For
LogFormat "%a %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" [pid %P]" combined

Thanks you @helpquick !!
