### ISSUE TITLE
Log Rotate not working for Master mysql.log

### ISSUE THREAD

**Issue by Brauadler** [MailCleaner/MailCleaner#529]
Hello @JohnMertz ,
after the update of **rotate_logs.sh**, the MySql Master section no longer saves and rotates **mysql.log** in the mysql_master folder, but rotates updater4mc.log as an empty file. This is triggered by the code from line 186-190. 

Before Update:
`if [ -x /usr/bin/savelog ]; then
for i in mysql.log; do
    if [ -s $VARDIR/log/mysql_master/$i ]; then
      savelog -p -c $DAYSTOKEEP -C $VARDIR/log/mysql_master/$i >/dev/null
    fi
  done
fi`

After Update: 
`if [ -x /usr/bin/savelog ]; then
    if [ -s $VARDIR/log/mysql_master/mysql.log ]; then
        savelog -p -c $DAYSTOKEEP -C $VARDIR/log/mysql_master/$i >/dev/null
    fi
fi`

The **parameter i** is no longer overwritten like before the commit. It still contains updater4mc.log as the last set value from this part of the script:

`if [ -x /usr/bin/savelog ]; then
    for i in update.log update2.log autolearn.log rules.log spam_sync.log mc_counts-cleaner.log downloadDatas.log summaries.log updater4mc.log; do
        if [ -e $VARDIR/log/mailcleaner/$i ]; then
            savelog -p -c $DAYSTOKEEP -C $VARDIR/log/mailcleaner/$i >/dev/null
        fi
    done
fi`

Either ` for i in mysql.log; do ... done` should be added again or like in the MySQL slave part of the script, the filename should be specified directly.

**Comment by JohnMertz** [comment]
Thanks!

It should, indeed be literal, like the slave. I will have this fixed shortly.

For when it is fixed: on older machines, updates are installed at 02:30, so you may benefit from forcing the update (or just do a `git pull` on `/usr/mailcleaner`). On newer machines, this was changed to 22:30, so the update will be installed before the next log rotation.

I will comment and close when the patch is merged.

**Comment by JohnMertz** [comment]
Merged in #531
