### ISSUE TITLE
Firewall empty of Fail2ban entries after execution of Updater4mc.sh

### ISSUE THREAD

**Issue by Brauadler** [MailCleaner/MailCleaner#533]
Hello @JohnMertz, 

at the moment it is increasingly necessary in my system that fail2ban works correctly and does its job. I noticed that the banned IPs are no longer blocked after 22:30 (updater4mc.sh execution -> IPs are back in exim1 log) and the next day after the automatic release of the IP I find an error entry in the standard fail2ban.log (/var/log/fail2ban.log).

> 2023-07-15 07:17:15,976 fail2ban.actions[110119]: WARNING [mc-exim] Unban XXX.XXX.XXX.XXX
> 2023-07-15 07:17:16,006 fail2ban.actions.action[110119]: ERROR   iptables -n -L INPUT | grep -q 'fail2ban-mc-exim[ \t]' returned 100
> 2023-07-15 07:17:16,006 fail2ban.actions.action[110119]: ERROR   Invariant check failed. Trying to restore a sane environment
> 2023-07-15 07:17:16,102 fail2ban.actions.action[110119]: ERROR   iptables -w -D INPUT -p tcp -m multiport --dports 25,465,587 -j fail2ban-mc-exim
> iptables -w -F fail2ban-mc-exim
> iptables -w -X fail2ban-mc-exim returned 100

 
After an extended search, I noticed that after running updater4mc.sh, the iptables were cleaned of fail2ban entries due to the firewall restart but the still valid f2b entries are not added back. There are entries in both the mc-exim and mc-exim-bl tables in the database at this time.
 
After I manually executed the following command from /etc/init.d/firewall, 
`fail2ban.py internal reload-fw firewall`
the entries were correctly present again.

Since everything worked correctly for me in the first third of the year, I assume that perhaps the change in the file _/etc/init.d/firewall (Line 44)_ (https://github.com/MailCleaner/MailCleaner/pull/519) causes the error. 
Since a **&** at the end of the line starts a background process that is terminated when the script ends, here is my question:
Is it possible that the main script is terminated too quickly and the fail2ban.py script cannot be run through completely?  Or are there other problems with the mentioned firewall fix?

**Comment by JohnMertz** [comment]
I think that you are exactly right, the reload is getting killed by the SIGHUP. I'll update the script to disown the child process so that it properly continues in the background.

**Comment by JohnMertz** [comment]
#534 should resolve this, although I'll test it on our cluster before merging. If you'd like to give it a try also, let me know if this solution works for you.

**Comment by Brauadler** [comment]
The solution also works on my mailcleaner instance. Thanks for the fix.

**Comment by JohnMertz** [comment]
Thanks for looking into it more or your machine. The issues were were initially trying to address with the original patch were meant to address an issue that our cluster, specifically were having and have since been resolved by changes elsewhere in our infrastructure, so I have no problem reverting this. I'll push the changes that you report to work shortly.

**Comment by JohnMertz** [comment]
Merged in #535
