### ISSUE TITLE
Growing folders for log_search and stats_search files

### ISSUE THREAD

**Issue by Brauadler** [MailCleaner/MailCleaner#542]
Hello,

over time the following two folders /var/mailcleaner/run/mailcleaner/log_search and /var/mailcleaner/run/mailcleaner/stats_search have accumulated a lot of data.

Since I'm not sure if these files are needed again after using them in the web portal, here's my question:
Is it possible to add a cleanup function like in  #540  and automatically clean these two folders from obsolete files?

**Comment by JohnMertz** [comment]
Merged in #544 
These files can be useful for a reasonable period, since they work as a cache for search results, allowing faster rendering of identical searches. However, most searches are unlikely to be repeated after a while, so this commit deletes any older than 30 days.
