### ISSUE TITLE
Removing a domain via API doesn't remove black and whitelist IPs for this domain from DB

### ISSUE THREAD

**Issue by bogdankruszewski** [MailCleaner/MailCleaner#558]
If you remove a domain via API (probably also via GUI, but haven't tested it), where previously where blacklist and whitelist IP addresses set in "Advanced features" of this domain, the DB entries won't be removed. If you later re-add this domain, the black and whitelist IPs are still there. This could lead to unexpected behaviour, because noone has in mind (and via API it's even impossible) to remove these lists from the DB.

**Comment by JohnMertz** [comment]
Thanks for the report. We will have to add that table to the list of items removed in the domain deletion task. This should not be too difficult, but I'll need to find some time to properly test it. Hopefully I'll have a patch in the next few days.

**Comment by JohnMertz** [comment]
This was also an issue for domains deleted in the Web. PR #559 should address it for both.
