### ISSUE TITLE
exim 4.97.1 update issue

### ISSUE THREAD

**Issue by cjrw42** [MailCleaner/MailCleaner#584]
Not seen the update automatically so ran the updater script manually:

ATTENTION: Cannot install Exim 4.97.1
Your existing exim configuration template{s):
/usr/mailcleaner/etc/exim/exim_stage1.conf_template_4.96
/usr/mailcleaner/etc/exim/exim_stage4.conf_template_4.96
contain modifications.
The modifications will not be carried over to the new template files automatically.
Please port your modifications to version of each of these files ending in '_4.97' or confirm that you are okay abandoning these modifications.
Once you are statisfied with the state of the '_4.97' templates run the following to force this update:

  bash /root/Updater4MC/updates/75_mc_exim_4.97.1.update --force
  
 .... but there is not 75_mc_exim_4.97.1.update on that path??

root@mailcleaner:~/Updater4MC/updates$ ls -al ./7*
-rw-r--r-- 1 root root  774 Jan 19  2022 ./70_watchdog_cron.update
-rw-r--r-- 1 root root 2269 Mar 10  2022 ./72_Update_CA_Certificates.update
-rw-r--r-- 1 root root 3930 Jun  8  2022 ./73_Add_ESET_EFS_AV_support.update
-rw-r--r-- 1 root root  622 Jun 15  2022 ./74_Fix_ESET_EFS_wrapper.update
-rw-r--r-- 1 root root  954 Jan 10 09:51 ./79_ed25519.update

However just running the standard updater script with --force appears to work

**Comment by JohnMertz** [comment]
You are correct. Each time there has been an upgrade (from 4.94 onward), we have the same procedure to verify that config templates are unmodified, as a new template will be used and we don't want your modifications to simply stop being used.

For this, I copy/rename the last update script and update it as necessary. I failed to update the script name, in this case. It is meant to ask you to use `--force` on itself. I'll update the script shortly.

Thanks.

**Comment by JohnMertz** [comment]
Patched https://github.com/MailCleaner/Updater4MC/commit/b463b7857d1b2ffa7ac2ae3ec830795939142603
