### ISSUE TITLE
exim service does not start

### ISSUE THREAD

**Issue by lansaloni** [MailCleaner/MailCleaner#587]
Mailcleaner has stopped working, exim services do not start:

```
$ /etc/init.d/mailcleaner restart
Stopping mailcleaner:
  Stopping Apache: stopped.
  Stopping Exim stage 1: No /opt/exim4/bin/exim found running; none killed.
stopped.
  Stopping Exim stage 2: No /opt/exim4/bin/exim found running; none killed.
stopped.
  Stopping Exim stage 4: No /opt/exim4/bin/exim found running; none killed.
stopped.
  Stopping MailScanner: stopped.
Newsletters daemon: critical (not running and required)
SpamAssassin daemon: critical (not running and required)
ClamAV daemon: critical (not running and required)
ClamSpam daemon: critical (not running and required)
  Stopping DCC client daemon: stopped.
  Stopping SNMP daemon: stopped.
  Stopping greylisting daemon: stopped.
  Stopping Statistics daemon: stopped.
  Stopping Preferences daemon: stopped.
  Stopping slave DB: Wait for mysqld to exit
 stopped.
stopped.
  Stopping master DB: Wait for mysqld to exit
.
.
 stopped.
stopped.
Starting mailcleaner:
  Starting master DB: started.
  Starting slave DB: started.
restarting...
  Stopping firewall: stopped.
  Starting firewall: started..
[ ok ] Restarting authentication failure monitor: fail2ban  Resyncing DB... .
done.
  Starting SNMP daemon: started.
  Starting Statistics daemon: started.
  Starting Preferences daemon: started.
  Starting Preferences daemon: not started
  Found 8286 matching expected PID (already running).
  Starting DCC client daemon: started.
ClamAV daemon: running
ClamSpam daemon: running
SpamAssassin daemon: running
Newsletters daemon: running
  Starting MailScanner: started.
  Starting Exim stage 4: /opt/exim4/bin/exim: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
started.
  Starting Exim stage 2: /opt/exim4/bin/exim: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
started.
  Starting Exim stage 1: /opt/exim4/bin/exim: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
started.
  Starting greylisting daemon: started.
  Starting Apache: started.
```

**Comment by JohnMertz** [comment]
libssl.so.1.1 is a shared library provided by OpenSSL which should be installed here `/usr/local/lib/libssl.so.1.1`. This is a dependency that should have already been installed prior to the latest Exim release. There are a couple of different versions of OpenSSL that get installed on MailCleaner by different methods, so I'm not 100% sure which version is missing strictly based on the file path. 

Note: You can see which libraries are required and which ones are satisfied by running `ldd /opt/exim4/bin/exim`

I think the simplest step would simply be to try to reinstall openssl `apt-get install --reinstall openssl`, then use the `ldd` command to see if the library exists.

In a pinch, you can just upload the attached version of the library to that path directly (note that you need to unzip it since GitHub doesn't accept the raw format.
[libssl.so.1.1.zip](https://github.com/MailCleaner/MailCleaner/files/14312688/libssl.so.1.1.zip)

**Comment by lansaloni** [comment]
/usr/local/lib/libssl.so.1.1 is present:
```
$ ls -l /usr/local/lib/libssl.so.1.1
-rwxr-xr-x 1 root root 694552 Feb 16 16:08 /usr/local/lib/libssl.so.1.1
```
the sha256sum hash of the file on my system and the one you provided are identical.

I also try to reinstall openssl without success.

```
$ ldd /opt/exim4/bin/exim
        linux-vdso.so.1 (0x00007ffcc1aca000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f5625e10000)
        libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007f5625bd9000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f56258d8000)
        libgdbm.so.3 => /usr/lib/x86_64-linux-gnu/libgdbm.so.3 (0x00007f56256d1000)
        libldap_r-2.4.so.2 => /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2 (0x00007f562547f000)
        liblber-2.4.so.2 => /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2 (0x00007f5625270000)
        libmysqlclient.so.18 => /opt/mysql5/lib/libmysqlclient.so.18 (0x00007f5624d60000)
        libperl.so.5.20 => /usr/lib/x86_64-linux-gnu/libperl.so.5.20 (0x00007f562499f000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f562479b000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f562457e000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f56241d3000)
        libssl.so.1.1 => not found
        libcrypto.so.1.1 => not found
        libpcre2-8.so.0 => /usr/local/lib/libpcre2-8.so.0 (0x00007f5623f7a000)
        libspf2.so.2 => /opt/exim4/lib/libspf2.so.2 (0x00007f5623d5d000)
        libopendmarc.so.2 => /opt/exim4/lib/libopendmarc.so.2 (0x00007f5623b50000)
        libsasl2.so.2 => /usr/lib/x86_64-linux-gnu/libsasl2.so.2 (0x00007f5623934000)
        libgnutls-deb0.so.28 => /usr/lib/x86_64-linux-gnu/libgnutls-deb0.so.28 (0x00007f562360e000)
        libssl.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f56233ad000)
        libcrypto.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f5622fb0000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f5622da8000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f5622a9d000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f5626027000)
        libnsl.so.1 => /lib/x86_64-linux-gnu/libnsl.so.1 (0x00007f5622885000)
        libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f5622675000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f562245a000)
        libp11-kit.so.0 => /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007f5622214000)
        libtasn1.so.6 => /usr/lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007f5622000000)
        libnettle.so.4 => /usr/lib/x86_64-linux-gnu/libnettle.so.4 (0x00007f5621dce000)
        libhogweed.so.2 => /usr/lib/x86_64-linux-gnu/libhogweed.so.2 (0x00007f5621b9f000)
        libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f562191c000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f5621706000)
        libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f56214fd000)
```

**Comment by JohnMertz** [comment]
So then the issue seems to be that the `/usr/local/lib/` directory is not in the `LD_LIBRARY_PATH`. This environmen variable tells programs where to look for shared libraries. It is defined by `/etc/ld.so.conf` (which should just have an `include` for all filed in the `/etc/ld.so.conf.d/` directory). On my system, at least, that path is included in `/etc/ld.so.conf.d/libc.conf`:

```
mc:$ cat /etc/ld.so.conf.d/libc.conf
# libc default configuration
/usr/local/lib
```

Please try creating or adding to that file and test `ldd` again (or just try restarting Exim).

I assume that this file should be created by the `libc6` package and it would be very concerning if that is not installed on your system. You may want to try `apt-get install libc6` (or `grep` for that package in the output of `dpkg -l`) just to be sure. If it does turn out that that package is missing, you should `grep` (or `zgrep` where necessary) for it's removal in `/var/log/apt/history.log*` to find out when/why it was removed.

**Comment by lansaloni** [comment]
What you indicate seems completely correct to me and the libc6 package is correctly installed:
```
$ dpkg -l | grep libc6
ii  libc6:amd64                           2.19-18+deb8u10                    amd64        GNU C Library: Shared libraries
ii  libc6-dev:amd64                       2.19-18+deb8u10                    amd64        GNU C Library: Development Libraries and Header Files
root@mailcleaner:/usr/local/lib$ cat /etc/ld.so.conf
include /etc/ld.so.conf.d/*.conf

root@mailcleaner:/usr/local/lib$ ls -l /etc/ld.so.conf.d/*.conf
-rw-r--r-- 1 root root 38 Oct  5  2014 /etc/ld.so.conf.d/fakeroot-x86_64-linux-gnu.conf
-rw-r--r-- 1 root root 44 Feb  6  2011 /etc/ld.so.conf.d/libc.conf
-rw-r--r-- 1 root root 48 May 18  2017 /etc/ld.so.conf.d/mailcleaner.conf
-rw-r--r-- 1 root root 68 Jun  6  2012 /etc/ld.so.conf.d/x86_64-linux-gnu.conf
root@mailcleaner:/usr/local/lib$ cat /etc/ld.so.conf.d/libc.conf
# libc default configuration
/usr/local/lib
root@mailcleaner:/usr/local/lib$ ls -la /usr/local/lib
total 2620
drwxrwsr-x  6 root staff    4096 Feb 16 17:13 .
drwxrwsr-x 10 root staff    4096 Dec  3  2014 ..
-rw-r--r--  1 root root   512998 Feb 15  2022 libpcre2-8.a
-rwxr-xr-x  1 root root      955 Feb 15  2022 libpcre2-8.la
lrwxrwxrwx  1 root root       20 Feb 15  2022 libpcre2-8.so -> libpcre2-8.so.0.10.1
lrwxrwxrwx  1 root root       20 Feb 15  2022 libpcre2-8.so.0 -> libpcre2-8.so.0.10.1
-rwxr-xr-x  1 root root   375912 Feb 15  2022 libpcre2-8.so.0.10.1
-rw-r--r--  1 root root     7642 Feb 15  2022 libpcre2-posix.a
-rwxr-xr-x  1 root root     1009 Feb 15  2022 libpcre2-posix.la
lrwxrwxrwx  1 root root       23 Feb 15  2022 libpcre2-posix.so -> libpcre2-posix.so.2.0.3
lrwxrwxrwx  1 root root       23 Feb 15  2022 libpcre2-posix.so.2 -> libpcre2-posix.so.2.0.3
-rwxr-xr-x  1 root root    11112 Feb 15  2022 libpcre2-posix.so.2.0.3
-rw-r--r--  1 root root  1040194 Jan 12 04:07 libssl.a
lrwxrwxrwx  1 root root       13 Jan 12 04:07 libssl.so -> libssl.so.1.1
-rwxr-xr-x  1 root root   694552 Jan 12 04:07 libssl.so.1.1
drwxrwsr-x  3 root staff    4096 May 18  2017 perl
drwxrwsr-x  4 root staff    4096 May 27  2020 python2.7
drwxrwsr-x  3 root staff    4096 Jul 26  2021 python3.4
drwxrwsr-x  3 root staff    4096 May 18  2017 x86_64-linux-gnu
```

however the LD_LIBRARY_PATH variable is set incorrectly:
```
$ echo $LD_LIBRARY_PATH
/opt/kaspersky/lib
```
It seems to me that Kaspersky is setting this variable incorrectly but I don't understand how.

**Comment by lansaloni** [comment]
`ldconfig -v` make the miracle!

**Comment by JohnMertz** [comment]
Great! I cannot tell you why it was a problem in the first place.

In `/var/mailcleaner/log/mailcleaner/updater4mc.log` (or whatever older version of this file contains the Exim 4.97.1 installation; should sometime since Wednesday), are there any errors during the `apt-get install`, after the fixes to the database columns?

It is okay if you don't feel like looking into this. I doubt that it is going to be a widespread issue, but it would be nice to have a better understanding of what might have gone wrong.

**Comment by lansaloni** [comment]
I also immediately thought of a problem due to an update and in fact I had manually installed the `mc-exim` package which had failed to update during the night, here is an extract from the file `/var/mailcleaner/log/mailcleaner/updater4mc. log.0` (which I attach in full [updater4mc.log.zip](https://github.com/MailCleaner/MailCleaner/files/14314754/updater4mc.log.zip)):

```
Fetched 9,746 kB in 22min 2s (7,368 B/s)
Reading package lists...
W: GPG error: http://archive.debian.org jessie Release: The following signatures were invalid: KEYEXPIRED 1587841717
Reading package lists...
Building dependency tree...
Reading state information...
pcre2 is already the newest version.
The following packages will be upgraded:
  mc-exim
1 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Need to get 931 kB of archives.
After this operation, 1,970 kB disk space will be freed.
WARNING: The following packages cannot be authenticated!
  mc-exim
Get:1 http://cdnmcpool.mailcleaner.net/ jessie/main mc-exim amd64 4.97.1 [931 kB]
Fetched 931 kB in 0s (1,851 kB/s)
(Reading database ... ^M(Reading database ... 5%^M(Reading database ... 10%^M(Reading database ... 15%^M(Reading database ... 20%^M(Reading database ... 25%^M(Reading database ... 30%^M(Reading database ... 35%^M(Reading database ... 40%^M(Reading database ... 45%^M(Reading database ... 50%^M(Reading database ... 55%^M(Reading database ... 60%^M(Reading database ... 65%^M(Reading database ... 70%^M(Reading database ... 75%^M(Reading database ... 80%^M(Reading database ... 85%^M(Reading database ... 90%^M(Reading database ... 95%^M(Reading database ... 100%^M(Reading database ... 64911 files and directories currently installed.)
Preparing to unpack .../mc-exim_4.97.1_amd64.deb ...
Unpacking mc-exim (4.97.1) over (4.96.2) ...
Setting up mc-exim (4.97.1) ...
Processing triggers for libc-bin (2.19-18+deb8u10) ...
Failed to install Exim 4.97.1
End of update.
Stopping mailcleaner:
  Stopping Apache: stopped.
  Stopping Exim stage 1: No /opt/exim4/bin/exim found running; none killed.
stopped.
  Stopping Exim stage 2: No /opt/exim4/bin/exim found running; none killed.
stopped.
  Stopping Exim stage 4: No /opt/exim4/bin/exim found running; none killed.
stopped.
  Stopping MailScanner: stopped.
```
but it didn't work, not even restarting the server (VM).

I solved it after giving the command to reload the LD cache.

**Comment by JohnMertz** [comment]
Hmm. Yes. It looks like it exitted during the processing of `libc-bin`. It must unlink the currently installed libraries, then re-link them later, but that later part never happened. I don't really have an explanation for this. Also strange that it did not do the same processing when you manually installed it.

It does not seem to be a widespread issue, so I'm just going to close this. If anyone else has the same problem, they can revive the issue and I'll look into it further.

Glad that it is working for you.

**Comment by Space895** [comment]
Hello John,

thanks for your help. We had the same issue like lansaloni describes at at least 3 mailcleaner installations running. They were all missing libssl.so.1.1. All three had patch-level: 2024012501 / 00-34bac5c. All 3 became critical in the night of thursday to friday.

At the the first installation (the biggest, handling around 30 Domains), we reinstalled from scratch and after installation manually start updater4mc.sh. It updated to 2024012901 / 86-34bac5c -> no problems.

The other ones we will try your advices.
If they don´t work, we will also reinstall from scratch. These are small instances handling aroung 2-5 domains.

We also have some customer were no problems appeared. All these customers running Version 20240129 / 86-34bac5c.

Hope this will help to find the issue.

BR and thanks for your work !

Florian

**Comment by Space895** [comment]
Hello John,

we tried your advices - similar issue like lansaloni had, we checked all the steps you describe in this post - but without success.
ldconfig -v did not work.

BR

Florian

**Comment by JohnMertz** [comment]
Hi,

In the case where `ldconfig -v` did not work, did you copy the library that I attached above to the proper location first? I would struggle to think of anything else if the library is there, but it is not possible to cache it. Other than maybe file permissions? (It should be owned by `root:root` with at least `644` permissions).

As for the actual problem, we obviously must have an issue with different machines having a different upgrade/install history. Depending on when they were installed, there must have been different Updater4MC scripts available, or different packages available in the repositories.

I think I'll have to just publish a custom SSL package and add a dependency to the mc-exim package, or just bundle the library into the mc-exim package.

**Comment by linusmic** [comment]
Hi John, I also tried to follow the steps here on two installations, but I had to revert exim to the earlier version.

These are errors found after the ldconfig and upgrade:

Starting Exim stage 4: /opt/exim4/bin/exim: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
started.
  Starting Exim stage 2: /opt/exim4/bin/exim: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
started.
  Starting Exim stage 1: /opt/exim4/bin/exim: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory

**Comment by linusmic** [comment]
On my machine it looks the same:

dpkg -l | grep mc-clamav
ii  mc-clamav                             0.103.8                            amd64        This package includes the specific clamav package used by MailCleaner.

I'm pretty sure  the following command gave me the right libcrypto.so.1.1
I will have to do it a ldd /opt/exim4/bin/exim | grep "libcrypto"

I will need to try to upgrade exim again to be sure now it is downgraded as otherwise the incoming mails stop.

**Comment by JohnMertz** [comment]
[libcrypto.so.1.1.txt](https://github.com/MailCleaner/MailCleaner/files/14339126/libcrypto.so.1.1.txt)

Can you see if that attachment works? Note that I don't think I mentioned the normal installation path previously: `/opt/clamav/lib/libcrypto.so.1.1`. Again, you might need to use `ldconfig` again to index it.

**Comment by linusmic** [comment]
Thank you for your help. Strangely the /opt/clamav/lib/libcrypto.so.1.1 was already there and it seemed to be identical with the one you provided. 

I run the ldconfig before and after the upgrade, but it didn't help. Why can't my system find/use my libcrypto.1.1 although it is present and ldconfig is run. Same errors still, for instance: "Starting Exim stage 4: /opt/exim4/bin/exim: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory" 

$ ls -la /opt/clamav/lib/ | grep "libcrypto"
-rw-r--r-- 1 root root 5754238 Jan 12 05:07 libcrypto.a
lrwxrwxrwx 1 root root      16 Jan 12 05:07 libcrypto.so -> libcrypto.so.1.1
-rwxr-xr-x 1 root root 3432928 Jan 12 05:07 libcrypto.so.1.1

**Comment by linusmic** [comment]
I also tried:

`export LD_LIBRARY_PATH=/opt/clamav/lib/:$LD_LIBRARY_PATH
`
`$ ldconfig
`
```
$ ldd /opt/exim4/bin/exim | grep "libcrypto"
	libcrypto.so.1.1 => /opt/clamav/lib/libcrypto.so.1.1 (0x00007fad85202000)
	libcrypto.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007fad83fde000)
```

```
$ /opt/exim4/bin/exim --version
Exim version 4.97.1 #1 built 12-Jan-2024 07:25:46
Copyright (c) University of Cambridge, 1995 - 2018
(c) The Exim Maintainers and contributors in ACKNOWLEDGMENTS file, 2007 - 2022
Probably GDBM (native mode)
Support for: Content_Scanning crypteq iconv() IPv6 Perl OpenSSL TLS_resume DANE DKIM DMARC DNSSEC Event OCSP PIPECONNECT PRDR Queue_Ramp SPF TCP_Fast_Open Experimental_ARC Experimental_DSN_info
Lookups (built-in): lsearch wildlsearch nwildlsearch iplsearch dbm dbmjz dbmnz dnsdb ldap ldapdn ldapm mysql
Authenticators: cram_md5 plaintext spa tls
Routers: accept dnslookup ipliteral iplookup manualroute queryprogram redirect
Transports: appendfile/maildir/mailstore/mbx autoreply lmtp pipe smtp
Malware: f-protd f-prot6d drweb aveserver fsecure kavdaemon sophie clamd mksd avast sock cmdline
Fixed never_users: 0
Configure owner: 1002:1002
Size of off_t: 8
Configuration file is /opt/exim4/etc/exim.conf

```

Unfortunately this didn't seem to have helped as the incoming, filtering and outgoing MTAs are still critical. I downgraded again to get traffic to go through. 

Is there anything I can do to get exim working? I'm thankful for any hint.

**Comment by JohnMertz** [comment]
Sorry for the delay. I have just uploaded a new version of the package with a statically linked version of the SSL/Crypto libraries bundled in. Can you try reinstalling with:
```
apt-get install --reinstall mc-exim
```

**Comment by linusmic** [comment]
Thank you for your help, I apprechiate you took the time. After running apt update and apt upgrade everything seems to work again, good messages going through and the version is the patched one.

```
/opt/exim4/bin/exim --version | grep "version"
Exim version 4.97.1 #1 built 27-Feb-2024 00:28:28

```

**Comment by JohnMertz** [comment]
Great! Thanks for confirming!
