### ISSUE TITLE
Remote host closed connection in response to EHLO

### ISSUE THREAD

**Issue by kovacicjanez** [MailCleaner/MailCleaner#598]
Hi,

mailcleaner suddenly can't deliver mail only to o365 servers:

Remote host closed connection in response to EHLO..

H=*******.mail.protection.outlook.com [52.101.68.21]: Remote host closed connection in response to EHLO mailcleaner.*******
2024-04-02 12:33:56 1rrbSl-000000001Qq-0kPx == someo365mail@o365mail.com R=dnslookup T=remote_smtp defer (-18) H=*******.mail.protection.outlook.com [52.101.68.21]: Remote host closed connection in response to EHLO mailcleaner.******

**Comment by alijundi** [comment]
Hello guys
Hello @JohnMertz 

I can confirm what @kovacicjanez  said above. I am not sure what is the problem here. All emails to outlook are beeing closed in response to EHLO

Please assist.

Thank you.

**Comment by kovacicjanez** [comment]
Hi,

Disable TLS/SSL in  Configuration-> SMTP
After that it should start working again

**Comment by juuso123** [comment]
> Hi,
> 
> Disable TLS/SSL in Configuration-> SMTP After that it should start working again

That disables TLS completely. I updated the TLS/SSL in Configuration-> SMTP certificates with new signed ones and it also seems to work.

**Comment by mjambor777** [comment]
Hello, 

> Disable TLS/SSL in Configuration-> SMTP After that it should start working again

thanks. It works, but I'm sure it's a temporary solution. Is there any new information on this?

**Comment by alijundi** [comment]
How do we update the certificate? I disabled it now and it is working. But, I would like to re-enable TLS with new certiricate. how do I create a new certificate

**Comment by juuso123** [comment]
You can look at this link: https://jdalyit.wordpress.com/2013/07/26/generating-and-applying-an-ssl-certificate-for-mailcleaner/ on how to create certificates.

**Comment by mjambor777** [comment]
> That disables TLS completely. I updated the TLS/SSL in Configuration-> SMTP certificates with new signed ones and it also seems to work.

Thanks a lot. It works! Thanks. I have an internal CA, but in my opinion a new certificate can be generated using openssl:

openssl req -new -newkey rsa:2048 -nodes -keyout privateKey.key -out certRequest.csr
openssl x509 -signkey privateKey.key -in certRequest.csr -req -days 3650 -sha256 -out certificate.crt

**Comment by alijundi** [comment]
Thank you @mjambor777 All works as expected. Appreciate your feedback. the two lines saved me some efforts.

**Comment by JohnMertz** [comment]
Hello all,

Last night I posted a new item to the InfoBox which should appear on the home screen of your MailCleaner administrator interface which addresses this and other deliverability issues.

Specifically, Office365 has implemented stricter policies for sender verification and security. Counter-intuitively, they have decided that no certificate at all (ie. plain-text email) is better than mail encrypted with an expired certificate, self-signed certificate, or certificate that is not valid for the sending host. This is why some of you saw message being delivered once TLS was disabled.

I don't think that generating your own certificate is the best solution in the long-term. It is possible that it will get things going, but it is only a matter of time before certain mail hosts start blocking these certificates also. Some already do.

I would recommend that all users get proper certificates that match the hostname of their MailCleaner machines and that are signed by a recognized Certificate Authority.

For Community Edition users, the free certificates provided by LetsEncrypt will work, you just need to keep them updated every couple of months. This is what I use on my personal machine. I have `certbot` automatically update the certificates in `/etc/letsencrypt`, then I use the following script to apply the certificates to MailCleaner via a cronjob that runs once each weekend:

```
#!/bin/bash

usage() {
    echo "Usage: $0 public_chain private_key"
    exit;
}

SRCDIR=`grep 'SRCDIR' /etc/mailcleaner.conf | cut -d ' ' -f3`

if [ ! $1 ] || [ ! $2 ]; then
    echo "Missing argument"
    usage
elif [[ ! -r $1 ]]; then
    echo "Cannot read $1"
    usage
elif [[ ! -r $2 ]]; then
    echo "Cannot read $2"
    usage
fi

CERT=`cat $1 | grep -m 1 -B 1000 'END CERTIFICATE'`
COUNT=`cat $1 | grep -c 'END CERTIFICATE'`
let "COUNT--"

if [ $COUNT ]; then
    CHAIN=`tac $1 | grep -m $COUNT -B 1000 'BEGIN CERTIFICATE' | tac`
else
    CHAIN=''
fi

cat << EOF | ${SRCDIR}/bin/mc_mysql -m mc_config
UPDATE mta_config set tls_certificate_data = '`cat $1`';
EOF

cat << EOF | ${SRCDIR}/bin/mc_mysql -m mc_config
UPDATE mta_config set tls_certificate_key = '`cat $2`';
EOF

for i in 1 4; do
    ${SRCDIR}/bin/command_to_cluster.sh "${SRCDIR}/etc/init.d/exim_stage$i restart"
done

cat << EOF | ${SRCDIR}/bin/mc_mysql -m mc_config
UPDATE httpd_config set tls_certificate_data = '`echo -e "$CERT"`';
EOF

cat << EOF | ${SRCDIR}/bin/mc_mysql -m mc_config
UPDATE httpd_config set tls_certificate_chain = '`echo -e "$CHAIN"`';
EOF

cat << EOF | ${SRCDIR}/bin/mc_mysql -m mc_config
UPDATE httpd_config set tls_certificate_key = '`cat $2`';
EOF

${SRCDIR}/bin/command_to_cluster.sh "${SRCDIR}/etc/init.d/apache restart"
```

Aside from this, please have a look at the other recommendations in the [deliverability tips article](https://support.mailcleaner.net/boards/3/topics/107-outgoing-relay-deliverability-tips). Valid SPF/DKIM/DMARC are increasingly becoming mandatory for delivery to some large hosting providers like Office365.
