### ISSUE TITLE
Documentation Download link broken

### ISSUE THREAD

**Issue by madpat1998** [MailCleaner/MailCleaner#604]
On your [website](https://www.mailcleaner.org/documentation/) you have linked some documentation PDF's.
The links just run into a timeout but when you try to access them without the "cdn" prefix, it will load.

Example:

Does NOT work:
https://cdn.mailcleaner.net/downloads/documentations/en/mailcleaner_user_manual.pdf

Does work
https://mailcleaner.net/downloads/documentations/en/mailcleaner_user_manual.pdf

**Comment by JohnMertz** [comment]
Thanks!

We were unfortunately caught off-guard by service changes by our CDN and as a result, the HTTP caching service no longer works. We cleaned up most of this (eg. cdnmcpool.mailcleaner.net repositories), but looks like we missed this one. I'll fix it shortly and then close the issue.

**Comment by JohnMertz** [comment]
Links fixed and also configured cdn.mailcleaner.net to redirect to mailcleaner.net
