### ISSUE TITLE
Mailclearner HYPER VM Admin password not working.

### ISSUE THREAD

**Issue by razaisb** [MailCleaner/MailCleaner#612]
i have try to use hypervm preconfigured vm . its admin password is not working as mentioned in setup file 

https://cdnpush.s3.us-east-2.stackpathstorage.com/vm/MailCleaner_VHDX_2023050201.zip

**Comment by JohnMertz** [comment]
Sorry that I did not notice this issue in a timely manner. There are new VM images available, can you confirm that the password works for these new images?
