### ISSUE TITLE
Where can i find latest iso?

### ISSUE THREAD

**Issue by ufo56** [MailCleaner/MailCleaner#62]
Hi

At homepage there is old 2014 iso only https://www.mailcleaner.org/download/

Any link where can i find latest community iso ?

**Comment by enoch85** [comment]
https://www.mailcleaner.org/latest-downloads/

**Comment by ufo56** [comment]
Thanks, yesterday that link did not open.

**Comment by reivilob** [comment]
Hi
this page is opening correctly from here ... you can also find it here:
https://www.mailcleaner.net/downloads/vm/
