### ISSUE TITLE
Downloaded bayes token and wordlist are not being installed anymore

### ISSUE THREAD

**Issue by MajorFault** [MailCleaner/MailCleaner#624]
Edition: Enterprise Edition
Version: 2024071201
Patch level: 91-26695ae

We noticed our /tmp partitions filling up with lots of bayes_toks_* and wordlist.db_* files due to a possible bug in CDN_fetch_bayes.sh. Those downloaded files are not moved to $VARDIR/spool/spamassassin/ anymore as the md5sum check fails.

CDN_fetch_bayes.sh:
https://github.com/MailCleaner/MailCleaner/blob/26695aea755752d6b5682f5a6db16ef95ed1c5e7/bin/CDN_fetch_bayes.sh#L90
and:
https://github.com/MailCleaner/MailCleaner/blob/26695aea755752d6b5682f5a6db16ef95ed1c5e7/bin/CDN_fetch_bayes.sh#L95

=> The "cut" command returns a whitespace as the 2nd field ( -f 2 ) is selected instead of the first field (which contains the md5 sum)

Changing the field to 1 should fix this:
Line 90: `    if [[ "$SA_SECRET" == "`md5sum /tmp/bayes_toks_$SA_SECRET | cut -d ' ' -f 1`" ]]; then`
Line 95: `    if [[ "$BOGO_SECRET" == "`md5sum /tmp/wordlist.db_$BOGO_SECRET | cut -d ' ' -f 1`" ]]; then`

**Comment by JohnMertz** [comment]
Thanks!

Do you want to open a pull request so that you get credit for fixing this?

**Comment by JohnMertz** [comment]
I checked our Watchdogs and a couple of customers were having issues with `/tmp` filling up their disk, so merging the patch was a priority. I took the liberty of fetching from your fork and adding another commit on top to remove any files that might have already built up. Merged in #625

**Comment by MajorFault** [comment]
Thank you @JohnMertz, appreciated!
