### ISSUE TITLE
Error spam_store

### ISSUE THREAD

**Issue by daniela030289** [MailCleaner/MailCleaner#636]
hello

I have the following problem, the mail was received in the mail cluster and it says completed but it was not delivered to the server.

I attach a reference image of the outgoing log and that it was classified as spam but the status was completed. the domain has tag configured.

![Screenshot 2024-09-04 170329](https://github.com/user-attachments/assets/92ce47a5-5489-4aca-aace-22844600975a)
![Screenshot 2024-09-04 165831](https://github.com/user-attachments/assets/15505238-82d1-463f-8553-0eb84163b50a)

**Comment by JohnMertz** [comment]
Hello,

Note that the determination of the status in Tracing is pretty clumsy. It looks for specific patterns within each of half a dozen different log files and updates based on the last one that has been seen without too much consideration of other context. So here, it is seeing 'Complete' as the most recent log in `/var/mailcleaner/log/exim_stage4/mainlog` and if it has not yet found any others which should supersede this then it just displays that result.

If it was detected as spam, there should be a 'Spam handling stage' section in the Tracing which reports how that spam is to be treated. ie:

* ... Message will be delivered using SendMeAnyway
* ... ready to be delivered with new id: ...
* ... status is spam: want tag, module: ...

Then it should get re-queued for the final delivery.

So, if you don't have this, it seems that it is still waiting to be processed by 'SpamHandler'. If this is the case, you should be able to find your message in `/var/mailcleaner/spool/exim_stage4/spamstore`.

The SpamHandler daemon is meant to constantly poll for messages in that directory, then evaluate the delivery settings and either quarantine, deliver or discard the message, as appropriate. Any of these actions should be logged for any message which ends up in the spamstore directory. So, like I said, this suggests it has not be processed. It's also possible that if failed to be written to that directory (eg. if the filesystem is full or in read-only mode).

If the file is still there, the simplest action is probably to just try to restart the SpamHandler daemon (Monitoring->Status, expand the Status column; or `/usr/mailcleaner/etc/init.d/spamhandler restart`).

**Comment by daniela030289** [comment]
I very much appreciate the additional information you can provide me because I can't get more information and the problem makes me desperate.

**Comment by JohnMertz** [comment]
At this point the item would have long expired from the queue. Typically the queue retention is 7 days by default. There is no way to recover it.

Are you still experiencing this issue with other messages?

**Comment by daniela030289** [comment]
Dear JohnMertz
Thanks you very much for all the help. Have a very good day.
