### ISSUE TITLE
API - Not able to set User attribute at Users authentication at domain

### ISSUE THREAD

**Issue by marceltoepler** [MailCleaner/MailCleaner#65]
I noticed that I am not able to set the value of field `User attribute` of `Users authentication` from a domain via API.

I checked the API source code to find out what's wrong and I found the issue.

In file [www/api/application/api/models/DomainAPI.php](https://github.com/MailCleaner/MailCleaner/blob/dc6c53f29634ce508ced390531f8fd4ff5d21c19/www/api/application/api/models/DomainAPI.php#L351) exists the following source code, beginning with line 345:
```
                 foreach (array(
                        'auth_server' => 'auth_server',
                        'auth_use_ssl' => 'use_ssl', 
                        'a_base_dn' => 'basedn', 
                        'a_bind_user' => 'binddn', 
                        'a_bind_pass' => 'bindpass',
                        'a_user_attr' => 'userattr',
                        'a_protocol_version' => 'ldapversion') as $key => $value) {
                    if (isset($params[$key])) {
                        $data[$value] = $params[$key];
                    }
                 } 
```

In function `getParamsString()` in file [www/guis/admin/application/forms/Domain/UserAuthentication/Ldap.php](https://github.com/MailCleaner/MailCleaner/blob/dc6c53f29634ce508ced390531f8fd4ff5d21c19/www/guis/admin/application/forms/Domain/UserAuthentication/Ldap.php#L144) it says:
`$fields = array('basedn', 'userattribute', 'binddn', 'bindpass', 'use_ssl', 'ldapversion');`

So the `userattr` value from `DomainAPI.php` doesn't math `userattribute` from `Ldap.php` and it get's removed.

**Fix for this issue:**
Replace `userattr` in file `DomainAPI.php` with `userattribute`.

**Comment by m-reka** [comment]
Hi @marceltoepler,

I'm testing your bug fix and come back to you ASAP.

Thank you for your report.

Regards,
Mentor

**Comment by m-reka** [comment]
Hi @marceltoepler,

I added your bug fix. Thank you for your contribution !

Regards,
Mentor
