### ISSUE TITLE
Missing LDAP mail attributes: mailPrimaryAddress, mailAlternativeAddress

### ISSUE THREAD

**Issue by taleteller** [MailCleaner/MailCleaner#86]
When trying to connect a MailCleaner to the LDAP directory of an existing Univention Corporate Server i noticed the following. While logon to the LDAP of Univention Server (using Port 7389 and vaild credentials) worked as well as getting ``result: passed`` when running "Test Authentication", there where no email addresses to be found.

Using an LDAP explorer connection to this server reveals that there are indeed attributes containing mail aliases listed. However the attribute where named: ``mailPrimaryAddress`` and ``mailAlternativeAddress``.

Checking the Code of MailCleaner i noticed the file ``www/classes/connector/fetcher/LDAPLookup.php`` is responsible for fetching the list of valid mail adressess. Since both of those are missing, the user is unable to log into the MailCleaner for configuration and checking the quarantine. 

Manual addition of the attribute names to ``$mail_attributes`` in this file fixes the problem and allows to work MailCleaner with UCS, and probably other openLDAP systems using this scheme, flawless.

**Comment by m-reka** [comment]
Hello @taleteller 

Thank you for your report !
Can you please open a PR with your proposal in order to make a clear review and tests it ?

Regards,
Mentor

**Comment by p-rolle** [comment]
Hello,

This was merged as you pointed out.
Thanks for it all

Best regards,
