### ISSUE TITLE
Forum admins anyone?

### ISSUE THREAD

**Issue by mbretter** [MailCleaner/MailCleaner#92]
Is the forum still alive? We tried to register several times, but the user accounts where never activated.

usernames: sysup, karlsteinscheisser

cheers

**Comment by reivilob** [comment]
Yes alive !
Perhaps you do not provide the requested information of your email bounce.
In these 2 situations the account is not activated
regards
Olivier

**Comment by mbretter** [comment]
Welcome email was received successfully, containing:
"Your account is currently inactive and will need to be approved by an
administrator before you can log in. Another email will be sent when this
has occurred."

however account is working now ...

thx,
cheers
